### ISSUE TITLE
Uncaught TypeError: Cannot call method 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by ramontayag** [codebrew/backbone-rails#107]
I'm new to backbone, but this doesn't look like it should be happening. I have a session model:

```
class OLBT.Models.Session extends Backbone.Model
  name: 'model'
  urlRoot: 'devise/sessions'
  defaults:
    sessionId: ''
    userId: ''
    email: ''
```

When I create a new model, `session = new OLBT.Models.Session()`, I get this error: `Uncaught TypeError: Cannot call method 'hasOwnProperty' of undefined`. Looks like `maybeUnwrap` is choking when no `args` are passed in. Not sure what this does yet, but checking if `typeof(args) != 'undefined'` before continuing fixes it.

Am I doing something wrong, or is this a valid issue?
